### ISSUE TITLE
version 0.5.0

### ISSUE THREAD

**Issue by alihassan0** [alihassan0/RGBolts#2]
### Purpose

Enhance Game Playability look and feel.
### TODO List
- [x] change HaxeFlixel default pixel Font.
- [x] Add Intro Screen 
- [x] add Animated Buttons using these [assets](http://www.gameart2d.com/free-casual-game-button-pack.html)
- [x] Add better bolts Sprites 
- [x] Fix object dragging offset.
- [x] Fix save/load System
- [x] Add better `objecetivePanel`
- [x] Change Color Pallette
- [ ] Change test cases UI to be more intuitive.
- [ ] enhance the tutorial
- [ ] change grid sprite.
- [ ] Add better level finished Screen.
- [ ] Change Blocks Icons
- [ ] Fix select test Case
- [ ] Add sounds
- [ ] Add consistent :hankey: art style :smile:
